language: node_js

node_js:
  - "5"

git:
  depth: 5  

install:
  - npm install -g gulp jspm typings
  - npm install gulp
  - npm -d install
  - jspm install
  - typings install

script:
  - gulp build
  - gulp test

