language: node_js

node_js:
  - "5"

git:
  depth: 5  
  
before_install:  
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - npm install -g gulp jspm typings
  - npm install gulp
  - npm -d install
  - jspm install
  - typings install

script:
  - gulp build
  - gulp test

